config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[ new create ]
  resources :users, only: %i[ show new create ]
  get "/sign_in", to: "sessions#new", as: :sign_in
  get "/sign_up", to: "users#new", as: :sign_up

  constraints(AuthenticatedConstraint.new) do
    resource :user, only: %i[ edit update destroy ]
    resources :sessions, only: %i[ destroy ]
    resources :posts, only: %i[ new create edit update destroy ] do
      resources :comments, only: %i[ create edit update destroy ], shallow: true
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount SolidErrors::Engine, at: "/errors"
  end

  resources :posts, only: %i[ index show ]

  namespace :benchmarking do
    post "read_heavy"
    post "write_heavy"
    post "balanced"
    post "post_create"
    post "comment_create"
    post "post_destroy"
    post "comment_destroy"
    post "post_show"
    post "posts_index"
    post "user_show"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier

  # ----- authenticated actions -----
  before_action :set_post, only: %i[ create ]
  before_action :set_and_authorize_comment, only: %i[ edit update destroy ]

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = @post.comments.new(comment_params)

    if @comment.save
      redirect_to post_path(@comment.post, anchor: dom_id(@comment)), notice: "Comment was successfully created."
    else
      @post = @comment.post
      render "posts/show", status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post, anchor: dom_id(@comment)), notice: "Comment was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy!
    redirect_to post_path(@comment.post), notice: "Comment was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_and_authorize_comment
      @comment = Comment.find(params[:id])
      raise ApplicationController::NotAuthorized, "not allowed to #{action_name} this comment" unless @comment.user == Current.user
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body).merge(user_id: Current.user.id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<details id="<%= dom_id comment %>" class="px-2" open>
  <summary class="cursor-pointer px-1 text-sm focus:outline-none focus-visible:ring ring-offset-2 ring-blue-500">
    <div class="inline-flex w-[calc(100%_-_1.676em)] items-baseline justify-between">
      <span>
        <% if controller_name == "users" %>
          <span>on <%= link_to comment.post.title, comment.post, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %></span>
        <% elsif controller_name == "posts" || controller_name == "comments" %>
          <span>by <%= link_to comment.user.screen_name, comment.user, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %></span>
        <% end %>
        <span>&middot;</span>
        <abbr title="<%= comment.created_at.to_formatted_s(:long) %>" class="cursor-help">
          <%= time_tag comment.created_at, time_ago_in_words(comment.created_at) %> ago
        </abbr>
      </span>

      <div class="flex justify-end gap-2">
        <% if comment.user == Current.user %>
          <%= link_to "Edit", edit_comment_path(comment), class: "border border-black text-black bg-white py-1 px-2 cursor-pointer hover:bg-black hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
          <%= button_to "Destroy", comment, method: :delete, class: "border border-red-500 text-red-500 bg-white py-1 px-2 cursor-pointer hover:bg-red-500 hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
        <% end %>
      </div>
    </div>
  </summary>

  <%= comment.body %>
</details>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div class="text-red-500 font-medium mb-8" role="alert">
      <h2 class="font-black text-sm uppercase tracking flex items-center">
        <%= I18n.t("errors.messages.not_saved", count: comment.errors.count, resource: comment.class.model_name.human.downcase) %>
      </h2>
      <ul class="list-[square] list-inside pl-4 mt-2">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-2 w-1/2 mb-8">
    <%= form.label :body, class: "sr-only" %>
    <%= form.text_area :body, rows: 3 %>
  </div>

  <div class="inline-block">
    <%= form.submit class: "border border-black text-black bg-white py-1 px-2 cursor-pointer hover:bg-black hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1 class="absolute -top-4 py-px px-2 -mx-2 uppercase font-bold text-lg">
  Editing comment
</h1>
<%= link_to "&larr; Back to post".html_safe, @comment.post, class: "absolute -top-4 right-4 py-px px-2 -mx-2 border-2 border-transparent hover:border-black focus:outline-none focus:ring focus:ring-offset-0 focus:ring-blue-500" %>
<%= render "form", comment: @comment %>