config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[ new create ]
  resources :users, only: %i[ show new create ]
  get "/sign_in", to: "sessions#new", as: :sign_in
  get "/sign_up", to: "users#new", as: :sign_up

  constraints(AuthenticatedConstraint.new) do
    resource :user, only: %i[ edit update destroy ]
    resources :sessions, only: %i[ destroy ]
    resources :posts, only: %i[ new create edit update destroy ] do
      resources :comments, only: %i[ create edit update destroy ], shallow: true
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount SolidErrors::Engine, at: "/errors"
  end

  resources :posts, only: %i[ index show ]

  namespace :benchmarking do
    post "read_heavy"
    post "write_heavy"
    post "balanced"
    post "post_create"
    post "comment_create"
    post "post_destroy"
    post "comment_destroy"
    post "post_show"
    post "posts_index"
    post "user_show"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true, length: { minimum: 5 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # ----- unauthenticated actions -----
  with_options only: %i[ index show ] do
    skip_before_action :ensure_user_authenticated!
    before_action :user_authenticated?
  end

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc).limit(50)
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
  end

  # ----- authenticated actions -----
  with_options only: %i[ edit update destroy ] do
    before_action :set_and_authorize_post
  end


  # GET /posts/new
  def new
    @post = Current.user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Current.user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
    redirect_to posts_url, notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_and_authorize_post
      @post = Post.find(params[:id])
      raise ApplicationController::NotAuthorized, "not allowed to #{action_name} this post" unless @post.user == Current.user
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div class="text-red-500 font-medium mb-8" role="alert">
      <h2 class="font-black text-sm uppercase tracking flex items-center">
        <%= I18n.t("errors.messages.not_saved", count: post.errors.count, resource: post.class.model_name.human.downcase) %>
      </h2>
      <ul class="list-[square] list-inside pl-4 mt-2">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-2 w-1/2 mb-8">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="flex flex-col gap-2 w-full mb-8">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10 %>
  </div>

  <div class="inline-block">
    <%= form.submit class: "border border-black text-black bg-white py-1 px-2 cursor-pointer hover:bg-black hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <% if controller_name == "posts" && action_name == "show" %>
    <%= post.title %>
  <% else %>
    <%= link_to post.title, post, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
  <% end %>
</div>
<small class="text-sm font-normal inline-flex items-baseline justify-between">
  <span>
    <% if controller_name == "posts" %>
      by <%= link_to (post.user == Current.user ? "you" : post.user.screen_name), user_path(post.user), class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
      <span>&middot;</span>
    <% end %>
    <abbr title="<%= post.created_at.to_formatted_s(:long) %>" class="cursor-help">
      <%= time_tag post.created_at, time_ago_in_words(post.created_at) %> ago
    </abbr>
    <span>&middot;</span>
    <%= pluralize post.comments_count, "comment" %>
  </span>
</small>

app/views/posts/edit.html.erb
<h1 class="absolute -top-4 py-px px-2 -mx-2 uppercase font-bold text-lg">
  Editing post
</h1>
<%= link_to "&larr; Back to posts".html_safe, posts_path, class: "absolute -top-4 right-4 py-px px-2 -mx-2 border-2 border-transparent hover:border-black focus:outline-none focus:ring focus:ring-offset-0 focus:ring-blue-500" %>

<%= render "form", post: @post %>

<div class="inline-block -ml-[0.15rem]">
  <%= link_to "Show this post", @post, class: "inline-block border border-transparent text-black bg-white py-1 px-2 cursor-pointer hover:border-black focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
</div>

app/views/posts/index.html.erb
<h1 class="absolute -top-4 py-px px-2 -mx-2 uppercase font-bold text-lg">
  Recent posts
</h1>
<% if Current.user %>
  <%= link_to "&plus; New post".html_safe, new_post_path, class: "absolute -top-4 right-4 py-px px-2 -mx-2 border-2 border-transparent hover:border-black focus:outline-none focus:ring focus:ring-offset-0 focus:ring-blue-500" %>
<% end %>

<div id="posts">
  <% if @posts.any? %>
    <table class="w-[calc(100%+2rem)] -mx-4 -mb-0">
      <tbody>
        <% @posts.each do |post| %>
          <tr class="*:px-4 *:py-2">
            <td>
              <% cache post do %>
                <%= render post %>
              <% end %>
            </td>
            <td class="flex justify-end gap-2">
              <% if post.user == Current.user %>
                <%= link_to "Edit", edit_post_path(post), class: "border border-black text-black bg-white py-1 px-2 cursor-pointer hover:bg-black hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
                <%= button_to "Destroy", post, method: :delete, class: "border border-red-500 text-red-500 bg-white py-1 px-2 cursor-pointer hover:bg-red-500 hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="flex items-center justify-center gap-2">
      <span class="">No posts yet&hellip; Want to be the first?</span>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="absolute -top-4 py-px px-2 -mx-2 uppercase font-bold text-lg">
  New post
</h1>
<%= link_to "&larr; Back to posts".html_safe, posts_path, class: "absolute -top-4 right-4 py-px px-2 -mx-2 border-2 border-transparent hover:border-black focus:outline-none focus:ring focus:ring-offset-0 focus:ring-blue-500" %>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1 class="absolute -top-4 py-px px-2 -mx-2 uppercase font-bold text-lg">
  <%= @post.title %>
</h1>
<%= link_to "&larr; Back to posts".html_safe, posts_path, class: "absolute -top-4 right-4 py-px px-2 -mx-2 border-2 border-transparent hover:border-black focus:outline-none focus:ring focus:ring-offset-0 focus:ring-blue-500" %>

<small class="absolute top-4 text-sm font-normal inline-flex items-baseline justify-between">
  <span>
    <% if controller_name == "posts" %>
      by <% if @post.user == Current.user %>
        you
      <% else %>
        <%= link_to @post.user.screen_name, user_path(@post.user), class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
      <% end %>
      <span>&middot;</span>
    <% end %>
    <%= time_ago_in_words(@post.created_at) %> ago
    <span>&middot;</span>
    <%= link_to pluralize(@post.comments_count, "comment"), url_for(anchor: :comments), class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
  </span>
</small>

<div class="mt-8 prose max-w-none text-black">
  <%= simple_format @post.description %>
</div>

<% if @post.user == Current.user %>
  <br>

  <div class="flex items-center gap-2">
    <%= link_to "Edit", edit_post_path(@post), class: "border border-black text-black bg-white py-1 px-2 cursor-pointer hover:bg-black hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
    <%= button_to "Destroy", @post, method: :delete, class: "border border-red-500 text-red-500 bg-white py-1 px-2 cursor-pointer hover:bg-red-500 hover:text-white focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
  </div>
<% end %>

<br>
<hr class="border-black border">
<br>

<% if Current.user.present? %>
  <%= render "comments/form", comment: @comment || @post.comments.new %>
<% end %>
<% if @post.comments.exists? %>
  <br />
  <div id="comments" class="space-y-4">
    <%= render @post.comments.order(created_at: :desc) %>
  </div>
<% end %>