config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[ new create ]
  resources :users, only: %i[ show new create ]
  get "/sign_in", to: "sessions#new", as: :sign_in
  get "/sign_up", to: "users#new", as: :sign_up

  constraints(AuthenticatedConstraint.new) do
    resource :user, only: %i[ edit update destroy ]
    resources :sessions, only: %i[ destroy ]
    resources :posts, only: %i[ new create edit update destroy ] do
      resources :comments, only: %i[ create edit update destroy ], shallow: true
    end

    mount MissionControl::Jobs::Engine, at: "/jobs"
    mount SolidErrors::Engine, at: "/errors"
  end

  resources :posts, only: %i[ index show ]

  namespace :benchmarking do
    post "read_heavy"
    post "write_heavy"
    post "balanced"
    post "post_create"
    post "comment_create"
    post "post_destroy"
    post "comment_destroy"
    post "post_show"
    post "posts_index"
    post "user_show"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title><%= content_for(:title) || "Lorem News" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="h-full flex flex-col max-w-4xl mx-auto p-8 pb-0 font-mono">
    <header class="flex items-center justify-between text-lg mb-16">
      <h2>
        <a href="/" class="bg-black text-white font-bold normal-case px-2 py-1 relative before:absolute before:inset-0 before:-z-10 before:transform before:bg-[radial-gradient(circle_at_center,#000_.05rem,transparent_0),radial-gradient(circle_at_center,#000_.05rem,transparent_0)] before:[background-size:.2rem_.2rem] before:[background-position:0_0,.1rem_.1rem] before:[background-color:initial] before:transition-transform before:ease-in before:duration-100 hover:before:translate-x-1 hover:before:translate-y-1 focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500">
          Lorem News
        </a>
      </h2>
      <div class="inline-flex items-center gap-2">
        <% if Current.user %>
          <span class="inline-flex items-center">
            <svg class="-ml-0.5 mr-1.5 h-2 w-2 text-green-500" fill="currentColor" height="8" width="8" viewBox="0 0 4 4">
              <rect width="4" height="4" />
            </svg>
            <span><%= link_to Current.user.screen_name_in_database, Current.user, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %></span>
          </span> |
          <%= button_to "Sign out", Current.session, method: :delete, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
        <% else %>
          <%= link_to "Sign in", sign_in_path, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %> |
          <%= link_to "Sign up", sign_up_path, class: "hover:underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500" %>
        <% end %>
      </div>
    </header>

    <main class="border-2 border-black bg-white px-4 py-8 relative mb-4 before:absolute before:inset-0 before:-z-10 before:transform before:translate-x-2 before:translate-y-2 before:bg-[radial-gradient(circle_at_center,#000_.05rem,transparent_0),radial-gradient(circle_at_center,#000_.05rem,transparent_0)] before:[background-size:.2rem_.2rem] before:[background-position:0_0,.1rem_.1rem] before:[background-color:initial]">
      <%= yield %>
    </main>

    <footer class="mt-auto text-sm text-center">
      <p class="py-4">
        Made with &heartsuit; by <a href="https://twitter.com/fractaledmind" class="underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500">@fractaledmind</a> for <a href="https://railsconf.org" class="underline focus:outline-none focus:ring focus:ring-offset-2 focus:ring-blue-500">RailsConf 2024</a>
      </p>
    </footer>

    <div class="absolute top-[4.5rem] left-0 right-0 text-center">
      <% if notice.present? %>
        <p role="alert" class="py-1 px-2 bg-white border border-green-500 text-green-500 font-medium inline-block">
          <%= notice.html_safe %>
        </p>
      <% end %>

      <% if alert.present? %>
        <p role="alert" class="py-1 px-2 bg-white border border-red-500 text-red-500 font-medium inline-block" data-controller="fade">
          <%= alert.html_safe %>
        </p>
      <% end %>
    </div>
  </body>
</html>